services:
    olx-server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - '4000:5000'
        env_file:
            - ./server/.env
        restart: unless-stopped
